config/routes.rb
NsaPanel::Engine.routes.draw do
  resources :users do
    post :order_drone_strike, on: :member

    resources :data
  end

  get '/check' => 'dashboard#law_accordance_check', as: :dashboard_law_accordance_check
  post '/proceed' => 'dashboard#proceed', as: :dashboard_proceed

  root to: 'dashboard#index'
end

app/controllers/nsa_panel/application_controller.rb
module NsaPanel
  class ApplicationController < ActionController::Base
    before_filter :authenticate, :require_warrant

    private

    def authenticate
      authenticate_or_request_with_http_basic("NSA Indirect Access Panel") do |username, password|
        NsaPanel.username == username && NsaPanel.password == password
      end
    end

    def require_warrant
      render 'nsa_panel/dashboard/law_accordance_check' unless has_warrant?
    end

    def has_warrant?
      session[:has_warrant] == true
    end

    def has_warrant!
      session[:has_warrant] = true
    end
  end
end

app/controllers/nsa_panel/dashboard_controller.rb
require_dependency "nsa_panel/application_controller"

module NsaPanel
  class DashboardController < ApplicationController
    skip_before_filter :require_warrant, only: [:proceed]

    def index
      redirect_to users_path
    end

    def law_accordance_check
    end

    def proceed
      has_warrant!
      redirect_to users_path
    end
  end
end

app/controllers/nsa_panel/data_controller.rb
require_dependency "nsa_panel/application_controller"

module NsaPanel
  class DataController < ApplicationController
    def index
      @user = NsaPanel.user.find(params[:user_id])
      @association = NsaPanel.association(params[:name])

      return render nothing: true unless @association

      @records = @user.send(@association.name).to_a
    end

    def show
      @user = NsaPanel.user.find(params[:user_id])
      @association = NsaPanel.association(params[:name])

      return render nothing: true unless @association

      @record = @user.send(@association.name).find(params[:id])
    end
  end
end

app/controllers/nsa_panel/users_controller.rb
require_dependency "nsa_panel/application_controller"

module NsaPanel
  class UsersController < ApplicationController
    def index
      @users = NsaPanel.user.all
    end

    def show
      @user = NsaPanel.user.find(params[:id])
    end

    def order_drone_strike
      @user = NsaPanel.user.find(params[:id])

      redirect_to users_path, notice: "Drone strike for #{@user.name} (##{@user.id}) was successfully ordered."
    end
  end
end

app/helpers/nsa_panel/application_helper.rb
module NsaPanel
  module ApplicationHelper
    def bootstrap_flash_class(name)
      name == :notice ? 'success' : name
    end
  end
end

app/helpers/nsa_panel/dashboard_helper.rb
module NsaPanel
  module DashboardHelper
  end
end

app/helpers/nsa_panel/data_helper.rb
module NsaPanel
  module DataHelper
  end
end

app/helpers/nsa_panel/users_helper.rb
module NsaPanel
  module UsersHelper
    def blackout(text, attribute)
      to_blackout = !%w[id name].include?(attribute)
      text = '_' * text.to_s.size if to_blackout
      content_tag(:span, text, class: to_blackout ? 'blackout' : '')
    end
  end
end

app/views/layouts/nsa_panel/_flashes.html.erb
<% flash.each do |name, message| %>
  <div class="alert alert-<%= bootstrap_flash_class name %>">
    <span><%= message %>
  </div>
<% end %>

app/views/layouts/nsa_panel/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NSA Panel</title>
  <%= stylesheet_link_tag    'nsa_panel/application', media: 'all' %>
  <%= javascript_include_tag 'nsa_panel/application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <div class="navbar">
      <div class="navbar-inner">
        <%= link_to 'NSA Indirect Access Panel', root_path, class: 'brand' %>

        <ul class="nav">
          <li><%= link_to 'Users', users_path %></li>
        </ul>
      </div>
    </div>

    <%= render partial: 'layouts/nsa_panel/flashes' %>

    <%= yield %>

    <footer>
      <%= image_tag 'nsa_panel/nsa-eagle-tiny.png' %>
    </footer>
  </div>
</body>
</html>

app/views/nsa_panel/dashboard/law_accordance_check.html.erb
<h3>We want to make sure you are accessing this portal in accordance with the law</h3>

<%= link_to 'I have received a FISA warrant', dashboard_proceed_path, method: :post, class: 'btn btn-large btn-block btn-success' %>
<%= link_to 'I have not received a FISA warrant', '#', class: 'btn btn-large btn-block btn-danger', id: 'no-warrant-btn' %>

app/views/nsa_panel/data/index.html.erb
<h1>
  <%= link_to @user.name, user_path(@user) %>'s
  <%= @association.name %>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.id %></td>
        <td><%= link_to 'I found this suspicious', user_datum_path(@user, record, name: @association.name), class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/nsa_panel/data/show.html.erb
<h1>
  <%= link_to @user.name, user_path(@user) %>'s
  <%= link_to @association.name.to_s.singularize, user_data_path(@user, name: @association.name) %>
  #<%= @record.id %>
</h1>

<%= image_tag 'nsa_panel/fuck_you.jpg' %>

app/views/nsa_panel/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></th>
        <td>
          <div class="btn-group">
            <%= link_to 'I think they are a terrorist', user_path(user), class: 'btn btn-primary' %>
            <%= link_to 'Strike with drone', order_drone_strike_user_path(user), method: :post, class: 'btn btn-warning' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/nsa_panel/users/show.html.erb
<h1>
  <%= @user.name %>
  <small>#<%= @user.id %></small>
</h1>

<%= link_to 'Strike with drone', order_drone_strike_user_path(@user), method: :post, class: 'btn btn-small btn-warning' %>

<h2>Attributes</h2>

<table class="table">
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
    </tr>
  </thead>

  <tbody>
    <% @user.attributes.each do |key, value| %>
      <tr>
        <td><%= key.capitalize %></td>
        <td><%= blackout value, key %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Related data</h2>

<ul>
  <% NsaPanel.associated_models.each do |association| %>
    <li><%= link_to association.name.capitalize, user_data_path(@user, name: association.name) %></li>
  <% end %>
</ul>